image: docker:18.02.0-git

before_script:
  - chmod +x ./linux/*.sh

stages:
  - Build
  - Production

Build-petri-image:
  stage: Build
  script:
    - docker login -u $DOCKER_ID_USER -p $DOCKER_USER_PASSWORD
    - docker build -t jaska/joona-frontend:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHA .
    - docker push jaska/joona-frontend

Deploy-production:
  stage: Production
  script:
    - ./linux/install_dependencies.sh
    - ./linux/setup_kubectl.sh
    - ./linux/install_tiller.sh
    - ./linux/helm_upgrade.sh