language: node_js
node_js:
  "7"
install:
  npm install

script:
  npm run build

after_success:
  - docker login -u $DOCKER_ID_USER -p $DOCKER_USER_PASSWORD
  - docker build -t $DOCKER_ID_USER/petri .
  - docker push $DOCKER_ID_USER/petri