language: node_js
node_js:
  "7"
install:
  npm install

script:
  npm run build

after_success:
  - docker login -u $DOCKER_ID_USER -p $DOCKER_USER_PASSWORD
  - export TAG=${TRAVIS_TAG:-latest}
  - docker build -t $DOCKER_ID_USER/petri .
  - docker tag $DOCKER_ID_USER/petri $DOCKER_ID_USER/petri:$TAG
  - docker push $DOCKER_ID_USER/petri

notifications:
  webhooks: http://salainen_kontti_updater.ths.tunk.org/