apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: petri
  labels:
    app: petri
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: petri
    spec:
      containers:
        - name: petri
          image: "{{ .Values.petriImage }}"
          ports:
            - containerPort: 80
          env:
            - name: SEPPO_IP
              value: seppo-service
            - name: SEPPO_PORT
              value: "80"
            - name: RISTO_IP
              value: risto-service
            - name: RISTO_PORT
              value: "80"