
export default {
    createComputer: (obj, {params}, context) => context.wompatti.createComputer(params),
    editComputer: (obj, {params}, context) => context.wompatti.editComputer(args.params),
    removeComputer: (obj, {id}, context) => context.wompatti.removeComputer(id),
    createDevice: (obj, {params}, context) => context.wompatti.createDevice(params),
    editDevice: (obj, {params}, context) => context.wompatti.editDevice(params),
    removeDevice: (obj, {id}, context) => context.wompatti.removeDevice(id),
    createKeyValue: (obj, {params}, context) => context.wompatti.createKeyValue(params),
    editKeyValue: (obj, {params}, context) => context.wompatti.editKeyValue(params),
    removeKeyValue: (obj, {id}, context) => context.wompatti.removeKeyValue(id),
    createWolInterface: (obj, {params}, context) => context.wompatti.createWolInterface(params),
    editWolInterface: (obj, {params}, context) => context.wompatti.editWolInterface(params),
    removeWolInterface: (obj, {id}, context) => context.wompatti.removeWolInterface(id),
    executeWolInterface: (obj, {id}, context) => context.wompatti.executeWolInterface(id),
    createDeviceType: (obj, {params}, context) => context.wompatti.createDeviceType(params),
    editDeviceType: (obj, {params}, context) => context.wompatti.editDeviceType(params),
    removeDeviceType: (obj, {params}, context) => context.wompatti.removeDeviceType(params),
    createCommand: (obj, {params}, context) => context.wompatti.createCommand(params),
    editCommand: (obj, {params}, context) => context.wompatti.editCommand(params),
    removeCommand: (obj, {id}, context) => context.wompatti.removeCommand(id),
    createTelnetInterface: (obj, {params}, context) => context.wompatti.createTelnetInterface(params),
    editTelnetInterface: (obj, {params}, context) => context.wompatti.editTelnetInterface(params),
    removeTelnetInterface: (obj, {id}, context) => context.wompatti.removeTelnetInterface(id),
    createSerialInterface: (obj, {params}, context) => context.wompatti.createSerialInterface(params),
    editSerialInterface: (obj, {params}, context) => context.wompatti.editSerialInterface(params),
    removeSerialInterface: (obj, {id}, context) => context.wompatti.removeSerialInterface(id)
}