type Language {
	id: ID
	name: String
}

type LanguagesConnection {
	languages: [Language]
	totalCount: Int
}

type CreateLanguageResponse {
	success: Boolean
	language: Language
}

type LanguageVariationsConnection {
	totalCount: Int
	variations: [Variation]
}
