type Mutation {
	createVariation(name: String, text: String): Variation
	updateVariation(params: UpdateVariationInputType): UpdateVariationResponse
	removeVariation(variationId: ID): Boolean
	createSongDatabase(name: String): SongDatabase
	updateSongDatabase(
		songDatabaseId: ID
		name: String
	): UpdateSongDatabaseResponse
	removeSongDatabase(songDatabaseId: ID): Boolean
	updateMatiasClient(
		matiasClientId: ID
		name: String
		accepted: Boolean
	): UpdateMatiasClientResponse
	createEwDatabase(
		name: String
		filesystemPath: String
		songDatabaseId: ID
		matiasClientId: ID
	): EwDatabase
	updateEwDatabase(
		ewDatabaseId: ID
		name: String
		accepted: Boolean
	): UpdateEwDatabaseResponse
	login(
		username: String
		password: String
		rememberMe: Boolean
		token: String
	): LoginResponse
	logout: LogoutResponse
	createAdminAccount(password: String!): CreateAdminAccountResponse
	createTag(name: String!): CreateTagResponse
	createLanguage(name: String!): CreateLanguageResponse
	createAuthor(name: String!): CreateAuthorResponse
	createCopyright(name: String!): CreateCopyrightResponse
}
