type Query {
	variation(variationId: ID): Variation
	searchVariations(
		searchWord: String
		songDatabaseId: ID
		tagId: ID
		languageId: ID
		offset: Int
		limit: Int
	): VariationsConnection
	newVariationVersion: VariationVersion
	songDatabase(songDatabaseId: ID!): SongDatabase
	songDatabaseVariations(
		songDatabaseId: ID!
	): SongDatabaseVariationsConnection
	variationsNotInSongDatabase(
		songDatabaseId: ID!
	): VariationsNotInSongDatabaseConnection
	searchSongDatabases(
		offset: Int
		limit: Int
		searchWord: String
		variationId: ID
	): SongDatabasesConnection
	matiasClient(matiasClientId: ID): MatiasClient
	searchMatiasClients: MatiasClientsConnection
	ewDatabase(ewDatabaseId: ID): EwDatabase
	searchEwDatabases(
		offset: Int
		limit: Int
		songDatabaseId: ID
		matiasClientId: ID
	): EwDatabasesConnection
	hasAdminAccount: Boolean
	viewer: Viewer
	searchTags(searchWord: String): TagsConnection
	searchLanguages(searchWord: String): LanguagesConnection
	searchAuthors(searchWord: String): AuthorsConnection
	searchCopyrights(searchWord: String): CopyrightsConnection
	variationTags(variationId: ID!): VariationTagsConnection
	variationSongDatabases(variationId: ID!): VariationSongDatabasesConnection
	tagVariations(tagId: ID!): TagVariationsConnection
	tag(tagId: ID!): Tag
	language(languageId: ID!): Language
	languageVariations(languageId: ID!): LanguageVariationsConnection
	author(authorId: ID!): Author
	authorVariations(authorId: ID!): AuthorVariationsConnection
	songDatabaseTags(songDatabaseId: ID!): SongDatabaseTagsConnection
}
