type SongDatabase {
	id: ID
	name: String
	variations: [Variation]
	tags: [Tag]
}

type SongDatabasesConnection {
	totalCount: Int
	songDatabases: [SongDatabase]
}

type SongDatabaseTagsConnection {
	totalCount: Int
	tags: [Tag]
}

type UpdateSongDatabaseResponse {
	success: Boolean
	songDatabase: SongDatabase
}
