type Tag {
	id: ID
	name: String
	variations: [Variation]
}

type TagsConnection {
	tags: [Tag]
	totalCount: Int
}

type VariationTagsConnection {
	totalCount: Int
	tags: [Tag]
}

type CreateTagResponse {
	success: Boolean
	tag: Tag
}
