type User {
	id: ID
	userName: String
}

type LoginResponse {
	user: User
	success: Boolean
	viewer: Viewer
}

type LogoutResponse {
	success: Boolean
	viewer: Viewer
}

type CreateAdminAccountResponse {
	user: User
	success: Boolean
}
