/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var ew_verse_pb = require('./ew_verse_pb.js');
goog.exportSymbol('proto.SeppoService.ChangeEwSongIdsRequest', null, global);
goog.exportSymbol('proto.SeppoService.ChangeEwSongIdsResponse', null, global);
goog.exportSymbol('proto.SeppoService.EwSong', null, global);
goog.exportSymbol('proto.SeppoService.InsertEwSongIdsRequest', null, global);
goog.exportSymbol('proto.SeppoService.InsertEwSongIdsResponse', null, global);
goog.exportSymbol('proto.SeppoService.NewSongId', null, global);
goog.exportSymbol('proto.SeppoService.VariationIdEwSongId', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SeppoService.EwSong = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.SeppoService.EwSong, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.SeppoService.EwSong.displayName = 'proto.SeppoService.EwSong';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SeppoService.EwSong.prototype.toObject = function(opt_includeInstance) {
  return proto.SeppoService.EwSong.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SeppoService.EwSong} msg The msg instance to transform.
 * @return {!Object}
 */
proto.SeppoService.EwSong.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    title: jspb.Message.getFieldWithDefault(msg, 2, ""),
    author: jspb.Message.getFieldWithDefault(msg, 3, ""),
    copyright: jspb.Message.getFieldWithDefault(msg, 4, ""),
    administrator: jspb.Message.getFieldWithDefault(msg, 5, ""),
    description: jspb.Message.getFieldWithDefault(msg, 6, ""),
    tags: jspb.Message.getFieldWithDefault(msg, 7, ""),
    text: jspb.Message.getFieldWithDefault(msg, 8, ""),
    variationid: jspb.Message.getFieldWithDefault(msg, 9, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SeppoService.EwSong}
 */
proto.SeppoService.EwSong.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SeppoService.EwSong;
  return proto.SeppoService.EwSong.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SeppoService.EwSong} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SeppoService.EwSong}
 */
proto.SeppoService.EwSong.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setAuthor(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setCopyright(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setAdministrator(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setTags(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setText(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setVariationid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SeppoService.EwSong.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SeppoService.EwSong.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SeppoService.EwSong} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.SeppoService.EwSong.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getAuthor();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getCopyright();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getAdministrator();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getTags();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getText();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getVariationid();
  if (f !== 0) {
    writer.writeUint32(
      9,
      f
    );
  }
};


/**
 * optional uint32 id = 1;
 * @return {number}
 */
proto.SeppoService.EwSong.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.SeppoService.EwSong.prototype.setId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string title = 2;
 * @return {string}
 */
proto.SeppoService.EwSong.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.SeppoService.EwSong.prototype.setTitle = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string author = 3;
 * @return {string}
 */
proto.SeppoService.EwSong.prototype.getAuthor = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.SeppoService.EwSong.prototype.setAuthor = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string copyright = 4;
 * @return {string}
 */
proto.SeppoService.EwSong.prototype.getCopyright = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.SeppoService.EwSong.prototype.setCopyright = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional string administrator = 5;
 * @return {string}
 */
proto.SeppoService.EwSong.prototype.getAdministrator = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.SeppoService.EwSong.prototype.setAdministrator = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * optional string description = 6;
 * @return {string}
 */
proto.SeppoService.EwSong.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.SeppoService.EwSong.prototype.setDescription = function(value) {
  jspb.Message.setField(this, 6, value);
};


/**
 * optional string tags = 7;
 * @return {string}
 */
proto.SeppoService.EwSong.prototype.getTags = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/** @param {string} value */
proto.SeppoService.EwSong.prototype.setTags = function(value) {
  jspb.Message.setField(this, 7, value);
};


/**
 * optional string text = 8;
 * @return {string}
 */
proto.SeppoService.EwSong.prototype.getText = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/** @param {string} value */
proto.SeppoService.EwSong.prototype.setText = function(value) {
  jspb.Message.setField(this, 8, value);
};


/**
 * optional uint32 variationId = 9;
 * @return {number}
 */
proto.SeppoService.EwSong.prototype.getVariationid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/** @param {number} value */
proto.SeppoService.EwSong.prototype.setVariationid = function(value) {
  jspb.Message.setField(this, 9, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SeppoService.VariationIdEwSongId = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.SeppoService.VariationIdEwSongId, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.SeppoService.VariationIdEwSongId.displayName = 'proto.SeppoService.VariationIdEwSongId';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SeppoService.VariationIdEwSongId.prototype.toObject = function(opt_includeInstance) {
  return proto.SeppoService.VariationIdEwSongId.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SeppoService.VariationIdEwSongId} msg The msg instance to transform.
 * @return {!Object}
 */
proto.SeppoService.VariationIdEwSongId.toObject = function(includeInstance, msg) {
  var f, obj = {
    ewsongid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    variationid: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SeppoService.VariationIdEwSongId}
 */
proto.SeppoService.VariationIdEwSongId.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SeppoService.VariationIdEwSongId;
  return proto.SeppoService.VariationIdEwSongId.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SeppoService.VariationIdEwSongId} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SeppoService.VariationIdEwSongId}
 */
proto.SeppoService.VariationIdEwSongId.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setEwsongid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setVariationid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SeppoService.VariationIdEwSongId.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SeppoService.VariationIdEwSongId.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SeppoService.VariationIdEwSongId} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.SeppoService.VariationIdEwSongId.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEwsongid();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getVariationid();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
};


/**
 * optional uint32 ewSongId = 1;
 * @return {number}
 */
proto.SeppoService.VariationIdEwSongId.prototype.getEwsongid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.SeppoService.VariationIdEwSongId.prototype.setEwsongid = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional uint32 variationId = 2;
 * @return {number}
 */
proto.SeppoService.VariationIdEwSongId.prototype.getVariationid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.SeppoService.VariationIdEwSongId.prototype.setVariationid = function(value) {
  jspb.Message.setField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SeppoService.NewSongId = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.SeppoService.NewSongId, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.SeppoService.NewSongId.displayName = 'proto.SeppoService.NewSongId';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SeppoService.NewSongId.prototype.toObject = function(opt_includeInstance) {
  return proto.SeppoService.NewSongId.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SeppoService.NewSongId} msg The msg instance to transform.
 * @return {!Object}
 */
proto.SeppoService.NewSongId.toObject = function(includeInstance, msg) {
  var f, obj = {
    oldewsongid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    newewsongid: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SeppoService.NewSongId}
 */
proto.SeppoService.NewSongId.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SeppoService.NewSongId;
  return proto.SeppoService.NewSongId.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SeppoService.NewSongId} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SeppoService.NewSongId}
 */
proto.SeppoService.NewSongId.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setOldewsongid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setNewewsongid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SeppoService.NewSongId.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SeppoService.NewSongId.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SeppoService.NewSongId} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.SeppoService.NewSongId.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOldewsongid();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getNewewsongid();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
};


/**
 * optional uint32 oldEwSongId = 1;
 * @return {number}
 */
proto.SeppoService.NewSongId.prototype.getOldewsongid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.SeppoService.NewSongId.prototype.setOldewsongid = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional uint32 newEwSongId = 2;
 * @return {number}
 */
proto.SeppoService.NewSongId.prototype.getNewewsongid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.SeppoService.NewSongId.prototype.setNewewsongid = function(value) {
  jspb.Message.setField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SeppoService.InsertEwSongIdsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.SeppoService.InsertEwSongIdsRequest.repeatedFields_, null);
};
goog.inherits(proto.SeppoService.InsertEwSongIdsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.SeppoService.InsertEwSongIdsRequest.displayName = 'proto.SeppoService.InsertEwSongIdsRequest';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.SeppoService.InsertEwSongIdsRequest.repeatedFields_ = [2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SeppoService.InsertEwSongIdsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.SeppoService.InsertEwSongIdsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SeppoService.InsertEwSongIdsRequest} msg The msg instance to transform.
 * @return {!Object}
 */
proto.SeppoService.InsertEwSongIdsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    ewdatabasekey: jspb.Message.getFieldWithDefault(msg, 1, ""),
    variationidewsongidsList: jspb.Message.toObjectList(msg.getVariationidewsongidsList(),
    proto.SeppoService.VariationIdEwSongId.toObject, includeInstance),
    newsongidsList: jspb.Message.toObjectList(msg.getNewsongidsList(),
    proto.SeppoService.NewSongId.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SeppoService.InsertEwSongIdsRequest}
 */
proto.SeppoService.InsertEwSongIdsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SeppoService.InsertEwSongIdsRequest;
  return proto.SeppoService.InsertEwSongIdsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SeppoService.InsertEwSongIdsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SeppoService.InsertEwSongIdsRequest}
 */
proto.SeppoService.InsertEwSongIdsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setEwdatabasekey(value);
      break;
    case 2:
      var value = new proto.SeppoService.VariationIdEwSongId;
      reader.readMessage(value,proto.SeppoService.VariationIdEwSongId.deserializeBinaryFromReader);
      msg.addVariationidewsongids(value);
      break;
    case 3:
      var value = new proto.SeppoService.NewSongId;
      reader.readMessage(value,proto.SeppoService.NewSongId.deserializeBinaryFromReader);
      msg.addNewsongids(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SeppoService.InsertEwSongIdsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SeppoService.InsertEwSongIdsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SeppoService.InsertEwSongIdsRequest} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.SeppoService.InsertEwSongIdsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEwdatabasekey();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getVariationidewsongidsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.SeppoService.VariationIdEwSongId.serializeBinaryToWriter
    );
  }
  f = message.getNewsongidsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.SeppoService.NewSongId.serializeBinaryToWriter
    );
  }
};


/**
 * optional string ewDatabaseKey = 1;
 * @return {string}
 */
proto.SeppoService.InsertEwSongIdsRequest.prototype.getEwdatabasekey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.SeppoService.InsertEwSongIdsRequest.prototype.setEwdatabasekey = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * repeated VariationIdEwSongId variationIdEwSongIds = 2;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.SeppoService.VariationIdEwSongId>}
 */
proto.SeppoService.InsertEwSongIdsRequest.prototype.getVariationidewsongidsList = function() {
  return /** @type{!Array.<!proto.SeppoService.VariationIdEwSongId>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.SeppoService.VariationIdEwSongId, 2));
};


/** @param {!Array.<!proto.SeppoService.VariationIdEwSongId>} value */
proto.SeppoService.InsertEwSongIdsRequest.prototype.setVariationidewsongidsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.SeppoService.VariationIdEwSongId=} opt_value
 * @param {number=} opt_index
 * @return {!proto.SeppoService.VariationIdEwSongId}
 */
proto.SeppoService.InsertEwSongIdsRequest.prototype.addVariationidewsongids = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.SeppoService.VariationIdEwSongId, opt_index);
};


proto.SeppoService.InsertEwSongIdsRequest.prototype.clearVariationidewsongidsList = function() {
  this.setVariationidewsongidsList([]);
};


/**
 * repeated NewSongId newSongIds = 3;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.SeppoService.NewSongId>}
 */
proto.SeppoService.InsertEwSongIdsRequest.prototype.getNewsongidsList = function() {
  return /** @type{!Array.<!proto.SeppoService.NewSongId>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.SeppoService.NewSongId, 3));
};


/** @param {!Array.<!proto.SeppoService.NewSongId>} value */
proto.SeppoService.InsertEwSongIdsRequest.prototype.setNewsongidsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.SeppoService.NewSongId=} opt_value
 * @param {number=} opt_index
 * @return {!proto.SeppoService.NewSongId}
 */
proto.SeppoService.InsertEwSongIdsRequest.prototype.addNewsongids = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.SeppoService.NewSongId, opt_index);
};


proto.SeppoService.InsertEwSongIdsRequest.prototype.clearNewsongidsList = function() {
  this.setNewsongidsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SeppoService.InsertEwSongIdsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.SeppoService.InsertEwSongIdsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.SeppoService.InsertEwSongIdsResponse.displayName = 'proto.SeppoService.InsertEwSongIdsResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SeppoService.InsertEwSongIdsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.SeppoService.InsertEwSongIdsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SeppoService.InsertEwSongIdsResponse} msg The msg instance to transform.
 * @return {!Object}
 */
proto.SeppoService.InsertEwSongIdsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SeppoService.InsertEwSongIdsResponse}
 */
proto.SeppoService.InsertEwSongIdsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SeppoService.InsertEwSongIdsResponse;
  return proto.SeppoService.InsertEwSongIdsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SeppoService.InsertEwSongIdsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SeppoService.InsertEwSongIdsResponse}
 */
proto.SeppoService.InsertEwSongIdsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SeppoService.InsertEwSongIdsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SeppoService.InsertEwSongIdsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SeppoService.InsertEwSongIdsResponse} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.SeppoService.InsertEwSongIdsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SeppoService.ChangeEwSongIdsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.SeppoService.ChangeEwSongIdsRequest.repeatedFields_, null);
};
goog.inherits(proto.SeppoService.ChangeEwSongIdsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.SeppoService.ChangeEwSongIdsRequest.displayName = 'proto.SeppoService.ChangeEwSongIdsRequest';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.SeppoService.ChangeEwSongIdsRequest.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SeppoService.ChangeEwSongIdsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.SeppoService.ChangeEwSongIdsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SeppoService.ChangeEwSongIdsRequest} msg The msg instance to transform.
 * @return {!Object}
 */
proto.SeppoService.ChangeEwSongIdsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    ewdatabasekey: jspb.Message.getFieldWithDefault(msg, 1, ""),
    newsongidsList: jspb.Message.toObjectList(msg.getNewsongidsList(),
    proto.SeppoService.NewSongId.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SeppoService.ChangeEwSongIdsRequest}
 */
proto.SeppoService.ChangeEwSongIdsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SeppoService.ChangeEwSongIdsRequest;
  return proto.SeppoService.ChangeEwSongIdsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SeppoService.ChangeEwSongIdsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SeppoService.ChangeEwSongIdsRequest}
 */
proto.SeppoService.ChangeEwSongIdsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setEwdatabasekey(value);
      break;
    case 2:
      var value = new proto.SeppoService.NewSongId;
      reader.readMessage(value,proto.SeppoService.NewSongId.deserializeBinaryFromReader);
      msg.addNewsongids(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SeppoService.ChangeEwSongIdsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SeppoService.ChangeEwSongIdsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SeppoService.ChangeEwSongIdsRequest} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.SeppoService.ChangeEwSongIdsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEwdatabasekey();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getNewsongidsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.SeppoService.NewSongId.serializeBinaryToWriter
    );
  }
};


/**
 * optional string ewDatabaseKey = 1;
 * @return {string}
 */
proto.SeppoService.ChangeEwSongIdsRequest.prototype.getEwdatabasekey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.SeppoService.ChangeEwSongIdsRequest.prototype.setEwdatabasekey = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * repeated NewSongId newSongIds = 2;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.SeppoService.NewSongId>}
 */
proto.SeppoService.ChangeEwSongIdsRequest.prototype.getNewsongidsList = function() {
  return /** @type{!Array.<!proto.SeppoService.NewSongId>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.SeppoService.NewSongId, 2));
};


/** @param {!Array.<!proto.SeppoService.NewSongId>} value */
proto.SeppoService.ChangeEwSongIdsRequest.prototype.setNewsongidsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.SeppoService.NewSongId=} opt_value
 * @param {number=} opt_index
 * @return {!proto.SeppoService.NewSongId}
 */
proto.SeppoService.ChangeEwSongIdsRequest.prototype.addNewsongids = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.SeppoService.NewSongId, opt_index);
};


proto.SeppoService.ChangeEwSongIdsRequest.prototype.clearNewsongidsList = function() {
  this.setNewsongidsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SeppoService.ChangeEwSongIdsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.SeppoService.ChangeEwSongIdsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.SeppoService.ChangeEwSongIdsResponse.displayName = 'proto.SeppoService.ChangeEwSongIdsResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SeppoService.ChangeEwSongIdsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.SeppoService.ChangeEwSongIdsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SeppoService.ChangeEwSongIdsResponse} msg The msg instance to transform.
 * @return {!Object}
 */
proto.SeppoService.ChangeEwSongIdsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SeppoService.ChangeEwSongIdsResponse}
 */
proto.SeppoService.ChangeEwSongIdsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SeppoService.ChangeEwSongIdsResponse;
  return proto.SeppoService.ChangeEwSongIdsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SeppoService.ChangeEwSongIdsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SeppoService.ChangeEwSongIdsResponse}
 */
proto.SeppoService.ChangeEwSongIdsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SeppoService.ChangeEwSongIdsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SeppoService.ChangeEwSongIdsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SeppoService.ChangeEwSongIdsResponse} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.SeppoService.ChangeEwSongIdsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};


goog.object.extend(exports, proto.SeppoService);
