/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.WompattiService.PageInfo', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.WompattiService.PageInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.WompattiService.PageInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.WompattiService.PageInfo.displayName = 'proto.WompattiService.PageInfo';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.WompattiService.PageInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.WompattiService.PageInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.WompattiService.PageInfo} msg The msg instance to transform.
 * @return {!Object}
 */
proto.WompattiService.PageInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    hasnextpage: jspb.Message.getFieldWithDefault(msg, 1, false),
    haspreviouspage: jspb.Message.getFieldWithDefault(msg, 2, false),
    startcursor: jspb.Message.getFieldWithDefault(msg, 3, ""),
    endcursor: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.WompattiService.PageInfo}
 */
proto.WompattiService.PageInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.WompattiService.PageInfo;
  return proto.WompattiService.PageInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.WompattiService.PageInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.WompattiService.PageInfo}
 */
proto.WompattiService.PageInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setHasnextpage(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setHaspreviouspage(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setStartcursor(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setEndcursor(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.WompattiService.PageInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.WompattiService.PageInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.WompattiService.PageInfo} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.WompattiService.PageInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHasnextpage();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getHaspreviouspage();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getStartcursor();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getEndcursor();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional bool hasNextPage = 1;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.WompattiService.PageInfo.prototype.getHasnextpage = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 1, false));
};


/** @param {boolean} value */
proto.WompattiService.PageInfo.prototype.setHasnextpage = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional bool hasPreviousPage = 2;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.WompattiService.PageInfo.prototype.getHaspreviouspage = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 2, false));
};


/** @param {boolean} value */
proto.WompattiService.PageInfo.prototype.setHaspreviouspage = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string startCursor = 3;
 * @return {string}
 */
proto.WompattiService.PageInfo.prototype.getStartcursor = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.WompattiService.PageInfo.prototype.setStartcursor = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string endCursor = 4;
 * @return {string}
 */
proto.WompattiService.PageInfo.prototype.getEndcursor = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.WompattiService.PageInfo.prototype.setEndcursor = function(value) {
  jspb.Message.setField(this, 4, value);
};


goog.object.extend(exports, proto.WompattiService);
